### ISSUE TITLE
Please add disclaimer to txt

### ISSUE THREAD

**Issue by userbig** [RIAEvangelist/peacenotwar#11] opened 2022-03-16 09:20 UTC
@RIAEvangelist @designdrop please add a disclaimer at top of the text with the URL of the library. 

Because I`m almost lost my shit when I see this file on desktop (and it was empty actually) and almost nuked my SSD.

Not good.

**Comment by RIAEvangelist** [comment] 2022-03-16 20:04
You are the second person to mention this. I will try to make the update tonight, unless someone makes a PR for it first.

**Comment by rSh4d0w** [comment] 2022-03-16 22:03
Recent unity engine hub 3.1.0 includes this apparently. we nuked our entire workstation drives today because employees keept bugging IT department about a weird .txt file appearing on their desktop.

**Comment by majorendian** [comment] 2022-03-17 00:52
@rSh4d0w you must be near ukraine or russia. it deletes/overwrites hard drives of people near the warzone

**Comment by ilvl** [comment] 2022-03-17 12:15
I also have the same issue (file is empty). Mac OS Monterey, Macbook with M1 chip. Please fix it coz it looks like virus without text inside.

And also I suggest to rename file to `STOP-WAR-IN-UKRAINE.txt`. Coz word `America` makes russians crazy :)

**Comment by Ebosch747** [comment] 2022-03-18 00:04
> @rSh4d0w you must be near ukraine or russia. it deletes/overwrites hard drives of people near the warzone

What if you're in America and you're using a VPN that connects you with a Russian IP? Now you aren't just harming Russian computers, but potentially people who have never even been to Russia! The entire idea of this malware is disgusting.

**Comment by EvilistMonkey** [comment] 2022-03-18 00:47
> I also have the same issue (file is empty). Mac OS Monterey, Macbook with M1 chip. Please fix it coz it looks like virus without text inside.
> 
> And also I suggest to rename file to `STOP-WAR-IN-UKRAINE.txt`. Coz word `America` makes russians crazy :)

The word "America" doesn't make Russians crazy you moron. They're just civilians trying to live their life through the hellscape of their shitty government tearing things apart.

**Comment by RIAEvangelist** [comment] 2022-03-30 04:22
Duplicate of #5 waiting to get npm access back.

**Closed by RIAEvangelist** 2022-03-30 04:22 UTC
